config/routes.rb
BookmarkApplication::Application.routes.draw do
  mount LikeDislike::Engine, at: '/'
  devise_for :user
  resources :categories

  get "site/index"
  get "site/about"
  resources :bookmarks
  resource :categories

  root 'site#index'

  

end

app/models/bookmark.rb
class Bookmark < ActiveRecord::Base

  belongs_to :user
  belongs_to :category

  acts_as_votable

  validates :user_id,:category_id, presence: true
  validates :title, length: { minimum: 5 }, presence: true
  validates :url, format: {with: Regexp.new(URI::regexp(%w(http https)))}, presence: true
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :bookmarks
  validates :name, :presence => true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :bookmarks

  acts_as_voter
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_bookmark, only: [:show, :edit, :update, :destroy]

  # GET /bookmarks
  # GET /bookmarks.json
  def index
    @bookmarks = Bookmark.all
  end

  # GET /bookmarks/1
  # GET /bookmarks/1.json
  def show
  end

  # GET /bookmarks/new
  def new
    @bookmark = Bookmark.new
  end

  # GET /bookmarks/1/edit
  def edit
  end

  # POST /bookmarks
  # POST /bookmarks.json
  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.user_id = current_user.id

    respond_to do |format|
      if @bookmark.save
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully created.' }
        format.json { render action: 'show', status: :created, location: @bookmark }
      else
        format.html { render action: 'new' }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bookmarks/1
  # PATCH/PUT /bookmarks/1.json
  def update
    respond_to do |format|
      if @bookmark.update(bookmark_params)
        format.html { redirect_to @bookmark, notice: 'Bookmark was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @bookmark.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookmarks/1
  # DELETE /bookmarks/1.json
  def destroy
    @bookmark.destroy
    respond_to do |format|
      format.html { redirect_to bookmarks_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
  def set_bookmark
    unless @bookmark = current_user.bookmarks.where(id: params[:id]).first
      flash[:alert] = 'Bookmark not found.'
      redirect_to root_url
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bookmark_params
      params.require(:bookmark).permit(:title, :url,:category_id, :is_shared)
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @category }
      else
        format.html { render action: 'new' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
    if current_user
      @bookmarks = current_user.bookmarks.order('created_at desc')
    else
      @bookmarks = Bookmark.where(is_shared: true).order('created_at desc')
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for(@bookmark) do |f| %>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :title %>
      <%= f.input :url %>
    </div>

    <div class="form-inputs">
      <%= f.input :category_id,:collection => Category.pluck(:name,:id),:include_blank => false %>
    </div>

    <div class="form-inputs">
      <%= f.input :is_shared, :label => "Is Shared" %>
    </div>

    <div class="form-actions">
      <%= f.button :submit %>
    </div>
<% end %>

app/views/bookmarks/edit.html.erb
<h1>Editing bookmark</h1>

<%= render 'form' %>

<%= link_to 'Show', @bookmark %> |
<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/index.html.erb
<h1>Listing bookmarks</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Url</th>
      <th>Votes</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @bookmarks.each do |bookmark| %>
      <tr>
        <td><%= bookmark.title %></td>
        <td><%= bookmark.url %></td>
        <td>
          <%= like_unlike_button(bookmark) %>
        </td>
        <td><%= link_to 'Show', bookmark, class: "button" %></td>
        <td><%= link_to 'Edit', edit_bookmark_path(bookmark), class: "button" %></td>
        <td><%= link_to 'Destroy', bookmark, method: :delete, data: { confirm: 'Are you sure?' }, class: "large red awesome" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bookmark', new_bookmark_path, class: "button" %>

app/views/bookmarks/new.html.erb
<h1>New bookmark</h1>

<%= render 'form' %>

<%= link_to 'Back', bookmarks_path %>

app/views/bookmarks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @bookmark.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @bookmark.category.try(:name) %>
</p>

<p>
  <strong>Url:</strong>
  <%= @bookmark.url %>
</p>

<%= link_to 'Edit', edit_bookmark_path(@bookmark), class: "button" %> |
<%= link_to 'Back', bookmarks_path, class: "button" %>

app/views/categories/_form.html.erb
<%= simple_form_for(@category) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<h1>Listing categories</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @category.name %>
</p>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7 ]> <html class="ie6" lang="en"> <![endif]-->
<!--[if IE 7 ]> <html class="ie7" lang="en"> <![endif]-->
<!--[if IE 8 ]> <html class="ie8" lang="en"> <![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--> <html lang="en"> <!--<![endif]-->
<head>
  <meta charset="utf-8" />
  <!-- Uncomment to make IE8 render like IE7 -->
  <!-- <meta http-equiv="X-UA-Compatible" content="IE=7" /> -->

  <!-- Set the viewport width to device width for mobile -->
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />

  <title><%= content_for?(:title) ? yield(:title) : "MyBookmarks" %></title>

  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "vendor/custom.modernizr" %>
  <%= csrf_meta_tags %>
</head>

<body>
<div class="row">
  <div class="large-12 columns">

    <!-- Navigation -->
    <div class="row">
      <div class="large-12 columns">

        <nav class="top-bar" data-topbar>
          <ul class="title-area">
            <!-- Title Area -->
            <li class="name">
              <h1><a href="/">MyBookmarks</a></h1>
            </li>
            <li class="toggle-topbar menu-icon">
              <a href="#">Menu</a>
            </li>
          </ul>

          <section class="top-bar-section">
            <!-- Right Nav Section -->
            <ul class="right">
              <li class="divider"></li>
              <% if current_user %>
                  <li><%= link_to 'New Bookmarks', bookmarks_path %></li>
                  <li class="divider"></li>

                  <li class="has-dropdown">
                    <%= link_to current_user.email, '#'%>
                    <ul class="dropdown">
                      <li><%= link_to 'Profile', edit_user_registration_path %></li>
                      <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
                      <li class="divider"></li>
                    </ul>
                  </li>
              <% else %>
                  <li><%= link_to 'Login', new_user_session_path %></li>
                  <li><%= link_to 'Register', new_user_registration_path %></li>
              <% end %>
            </ul>
          </section>
        </nav>
        <!-- End Top Bar -->
      </div>
    </div>
    <!-- End Navigation -->

    <!-- Flash messages -->
    <div class="row">
      <div class="large-12 columns">
        <% if flash[:notice] %>
            <div data-alert class="alert-box success">
              <a href="#" class="close">&times;</a>
              <%= flash[:notice] %>
            </div>
        <% end %>

        <% if flash[:alert] %>
            <div data-alert class="alert-box alert">
              <a href="#" class="close">&times;</a>
              <%= flash[:alert] %>
            </div>
        <% end %>
      </div>
    </div>
    <!-- End Flash messages -->

    <!-- Content -->
    <div class="row">
      <div class="large-12 columns">
        <%= yield %>
      </div>
    </div>
    <!-- End Content -->

    <!-- Footer -->
    <footer class="row">
      <div class="large-12 columns"><hr />
        <div class="row">
          <div class="large-6 columns">
            <p>&copy; Copyrights by @kish</p>
          </div>

          <div class="large-6 columns">
            <ul class="inline-list right">
              <li><%=link_to "About", site_about_path%></li>
              <li><a href="https://twitter.com/kishorevlrtn">Twitter</a></li>
              <li><a href="https://www.facebook.com/kishore.mohan.165">Facebook</a></li>
            </ul>
          </div>
        </div>
      </div>
    </footer>
    <!-- End Footer -->

  </div>
</div>

<%= javascript_include_tag "application" %>
</body>
</html>

app/views/site/index.html.erb
<% unless current_user %>
    <div class="panel">
      <h1>Share your bookmarks!</h1>
      <p>A simple app to track and share your beloved bookmarks with others.</p>
      <%= link_to "Get started today", new_user_registration_path, :class => "button button-large" %>
    </div>
<%end%>

<h2>Latest Bookmarks</h2>
<table style="width: 100%">
  <thead>
  <tr>
    <th>Bookmark Category</th>
    <th>Url</th>
  </tr>
  </thead>

  <tbody>
  <% @bookmarks.each do |bookmark| %>
      <tr>
        <h1>
          <td><%= bookmark.category.try(:name)%></td>
        </h1>

        <h1>
          <td><%= link_to bookmark.title, bookmark.url %></td>
        </h1>
      </tr>
  <% end %>
  </tbody>
</table>

<hr>

<div class="row">
  <div class="large-8 columns">
    <h3>My Bookmarks</h3>
    <p>
      Let's store your bookmarks and share your favourite bookmarks to everybody.
    </p>
    <p><a class="button [secondary success alert]" href="http://github.com/kishore-mohan" target="_blank">Learn more</a>.</p>
  </div>
  <div class="large-4 columns">
    <h3>About this app</h3>
    <p>This is a tutorial app developed by <a href="http://github.com/kishore-mohan" target="_blank">Kishore Mohan</a> as a companion to the rails article. Check the source code on <a href="http://github.com/kishore-mohan/bookmark-application" target="_blank">GitHub</a>. </p>
  </div>
</div>